In [2]:
import numpy as np

# Criando arrays

## Usando listas

In [3]:
lst1 = [1, 2, 3]
ar1 = np.array(lst1)
ar2 = np.array([4, 5, 6])
ar3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
ar1

array([1, 2, 3])

In [5]:
ar2

array([4, 5, 6])

In [6]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Arrays somente com 0s

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# array de zero de tipo inteiro	
np.zeros((5, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# Array de zeros de tipo float
np.zeros((5, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Arrays somente com 1s

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# array de 1s de tipo inteiro
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# array de 1s de tipo float
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Usando range

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# (start, stop, step)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Outros arrays

In [17]:
# Matriz idendidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Matriz full
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [19]:
# Array com inteiros aleatórios
np.random.randint(10, size=(3, 6)) # Array 3x6 com inteiros de 0 a 9

array([[9, 8, 3, 7, 9, 5],
       [6, 1, 3, 3, 7, 4],
       [7, 7, 4, 6, 0, 4]], dtype=int32)

In [20]:
# Array com float aleatórios
np.random.rand(5, 3)

array([[0.94185166, 0.19586121, 0.98941734],
       [0.54116111, 0.78739324, 0.86387224],
       [0.13160832, 0.85170814, 0.09456444],
       [0.09160346, 0.99339833, 0.85718893],
       [0.53622678, 0.6959227 , 0.81086188]])

# Atributos

In [21]:
ar_rand = np.random.randint(10, size=(3, 2, 4)) # Array de 3 dimensões com valores de 0 a 9

In [22]:
print(f"Dimensão: {ar_rand.ndim}")
print(f"Shape: {ar_rand.shape}")
print(f"Tamanho: {ar_rand.size}")
print(f"dtype: {ar_rand.dtype}")
print(f"itemsize: {ar_rand.itemsize} bytes")
print(f"nbytes: {ar_rand.nbytes} bytes")

Dimensão: 3
Shape: (3, 2, 4)
Tamanho: 24
dtype: int32
itemsize: 4 bytes
nbytes: 96 bytes


# Operações com arrays

In [41]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
m3 = np.random.randint(10, size=(3, 3))
m4 = np.random.randint(10, size=(3, 3))

In [51]:
m3

array([[6, 4, 4],
       [1, 1, 1],
       [9, 4, 4]], dtype=int32)

In [52]:
m4

array([[2, 9, 1],
       [0, 6, 4],
       [2, 5, 1]], dtype=int32)

## Operações aritméticas

In [42]:
m1 + m2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [43]:
m1 - m2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [44]:
m1 * m2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [45]:
m1 / m2

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

## Operações com escalares

In [46]:
m1 + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
m2 * 5

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

In [48]:
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Multiplicação de matrizes

In [49]:
m1 @ m2

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [50]:
np.dot(m3, m4)

array([[ 20,  98,  26],
       [  4,  20,   6],
       [ 26, 125,  29]], dtype=int32)

## Arrays booleanos

In [53]:
m1 > m2

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [54]:
m3 == m4

array([[False, False, False],
       [False, False, False],
       [False, False, False]])